#! /usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from os import path

from MaggotDict import *
from MaggotDict.pretzel.app import *

def Main (app):
    if len (sys.argv) < 2:
        sys.stderr.write ('Usage: {} <word>\n'.format (path.basename (sys.argv [0]))) 
        sys.exit (1)

    console = Console (sys.stdout)
    with Dictionary (logger = app.Logger) as dictionary:
        word = ' '.join (sys.argv [1:])
        try:
            for name, entry in dictionary [word]:
                console.Write ('[{}]\n'.format (' {} '.format (name).center (78, '='))) # '\u2015'
                entry.ToConsole (console)
                console.Write ('\n')
        except KeyError:
            app.Log.Error ('word "{}" was not found'.format (word))
            
if __name__ == '__main__':
    Application (Main, 'maggot-dict-cli', console = True)
# vim: nu ft=python columns=120 :
